### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by syamimerinin** [magic-wormhole/magic-wormhole-mailbox-server#18]
Can i make request here?

Magic wormhole services is so awesome and I want to cry .I am more interested to run my own server whether for the rendezvous server(mailbox server) and relay server. Currently succeed with installing the docker for the relay,but for the mailbox server,i see none.

Can the rendezvous server also have docker file?

**Comment by nooitaf** [comment]
Here is all you need in your dockerfile..

```dockerfile
FROM python:3.8
RUN pip install magic-wormhole-mailbox-server
CMD [ "twist", "wormhole-mailbox","--usage-db=usage.sqlite" ] 
```

Then you build and run it ..
```shell
$ docker build -t magicwormhole Dockerfile
$ docker run -p 4000:4000 -d magicwormhole
```

And use this to connect..
```shell
$ wormhole --relay-url=ws://localhost:4000/v1 send FILENAME
```

**Comment by syamimerinin** [comment]
Thank you so much.

**Comment by meejah** [comment]
Ideally if that was expressed as a pull-request we could merge it :)

**Comment by nooitaf** [comment]
Sure, i made a pull request for the readme for a basic docker setup :)
As i'm no security expert and there are lot's of different ways of doing it, i kept it simple.
https://github.com/magic-wormhole/magic-wormhole-mailbox-server/pull/21
