### ISSUE TITLE
Server hangs up the websocket connection on the receiver side when PAKE is bad

### ISSUE THREAD

**Issue by piegamesde** [magic-wormhole/magic-wormhole-mailbox-server#22]
I'm trying to debug the handling of wrong password inputs in the Rust implementation, and I'm starting to think that this is a server error (or the specification is under-specced). To reproduce:

On the Python side run `venv/bin/wormhole --debug-state wormhole send someFile` (it works with sending from the Rust implementation as well. You don't really need the debug options, but it's still nice to have just in case).

On the Rust side, check out the `error-handling` branch and run `cargo run -- --log receive`

The last log messages are (shortened):

```
[magic_wormhole::core] State: Keying(KeyMachine { side: MySide(f0aaeb366b), versions: {}, nameplate: Some(Nameplate("6")), mailbox_machine: MailboxMachine { mailbox: uu2iyxmh6lcko, side: MySide(f0aaeb366b), processed: [pake], pending_outbound: {  } } , state: S2Unverified { key: <censored>, message_queue: <0 items> } })
[magic_wormhole::core] Processing: BounceMessage(EncryptedMessage { side: TheirSide(adb6ea0366), phase: version, body: <59 encypted bytes>)

[magic_wormhole::core] State: Keying(KeyMachine { side: MySide(f0aaeb366b), versions: {}, nameplate: Some(Nameplate("6")), mailbox_machine: MailboxMachine { mailbox: uu2iyxmh6lcko, side: MySide(f0aaeb366b), processed: [pake, version], pending_outbound: {  } } , state: Error })
[magic_wormhole::core] Processing: Shutdown(Err(PakeFailed))

[magic_wormhole::core] State: Closing { await_nameplate_release: true, await_mailbox_close: true, result: Err(PakeFailed) }
[magic_wormhole::core] Processing: ToIO(Close { mailbox: uu2iyxmh6lcko, mood: Scared })

[magic_wormhole::core] State: Closing { await_nameplate_release: true, await_mailbox_close: true, result: Err(PakeFailed) }
[magic_wormhole::core] Processing: ToIO(Release(6))

[magic_wormhole::core] Stopping wormhole event loop because of IO Error: WebSocket protocol error: Connection reset without closing handshake
[magic_wormhole::core] Stopped wormhole event loop
```

The first incoming message is the versions message. The verification fails and an error shutdown is initialized. The implementation now sends the `Close` and `Release` messages in exactly the same way as the sender side does. But the server does not handle these messages and simply hangs up the WebSockets connection for some reason.

From the logs, I don't think my code is doing anything wrong. On the other hand, it somehow works with the Python implementation

**Comment by warner** [comment]
Is the order of the close/release messages the same as the python version? I'd have to think more carefully about it, but I think maybe the Release is supposed to happen before the Close.

**Comment by piegamesde** [comment]
Oh of course, thank you!
