### ISSUE TITLE
Drop python2.7?

### ISSUE THREAD

**Issue by meejah** [magic-wormhole/magic-wormhole-mailbox-server#35]
This repository still claims to support python2.7, however the work to maintain that will only got up -- lots of libraries are dropping py27 support (and a recent PR seems to indicate the version of Automat we end with no longer works with py27).

**Comment by piegamesde** [comment]
Python 2 is EOL for so long, I don't think there is any need for much discussion here. Even major distros (IIRC at least Fedora, Nix, Gentoo) have actively started efforts of removing as much Python 2 code from their packages as possible. So even if this application *did* still maintain Python 2 support, it would likely not be packaged in a way that allows running it with Python 2 whatsoever.

**Comment by meejah** [comment]
Probably "python 3.5" too...

**Comment by pgajdos** [comment]
+ `six` is not used anywhere, so I guess it can be removed from install_requires, right?
