### ISSUE TITLE
Implement sending files using CDC (Content-Delivery-Chanking) [feature request]

### ISSUE THREAD

**Issue by ss256100** [magic-wormhole/magic-wormhole-mailbox-server#44]
Hello guys!
Its just feature request. I think will be nice to add CDC support for tool like that. 
I post it here just in case someone has time to add support of it in wormhole.

Here some rust lib which can help with it: https://github.com/rustic-rs/cdc

**Comment by meejah** [comment]
What's the use-case for this?

In any event, it's very unlikely the server repository (this one) is the correct place to suggest such a feature; the content is encrypted by clients, so one of the client implementations would be the right place to do some sort of hashing like this
